#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (rgba32f, binding = 0) uniform image2D u_Image;

void main()
{
    ivec2 position = ivec2(gl_GlobalInvocationID.xy);
    vec2 coord = position / vec2(gl_NumWorkGroups.xy);

    // float aspect = gl_NumWorkGroups.y / gl_NumWorkGroups.x;
    // coord.x *= aspect;

    vec2 root = imageLoad(u_Image, position).xy;
    float d = distance(coord, root);
    imageStore(u_Image, position, vec4(vec3(d), 1.));
}
