#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout (rgba32f, binding = 0) uniform image2D u_Input;
layout (rgba32f, binding = 1) uniform image2D u_Output;

void main()
{
    ivec2 position = ivec2(gl_GlobalInvocationID.xy);
    vec2 norm = position / vec2(gl_NumWorkGroups.xy);

    float alpha = imageLoad(u_Input, position).a;
    vec4 color = vec4(norm, 0., 1.) * step(1., alpha);

    imageStore(u_Output, position, color);
}
